# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST http://localhost:5199/Drone/Register
Content-Type application/json

{
    "SerialNumber":"123",
    "Model":"Lightweight",
    "State":"IDLE"
}

